import { createFileRoute } from "@tanstack/react-router";
import { Header } from "@/components/store/Header";
import { Footer } from "@/components/store/Sections";
import { CartDrawer } from "@/components/store/CartDrawer";
import { CartProvider } from "@/components/store/cart";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { listProducts } from "@/lib/products.functions";
import { getCategoryContent } from "@/lib/category-content.functions";
import { ProductCard } from "@/components/store/ProductCard";
import { Loader2, Leaf } from "lucide-react";
import { Reveal } from "@/components/store/Reveal";
import { PageLoader } from "@/components/store/PageLoader";

export const Route = createFileRoute("/category/$id")({
  component: CategoryPageWrapper,
});

const categoryImages: Record<string, string> = {
  "vegetable-seeds": "/vegetable-seeds-banner.png",
  "herb-seeds": "/herb-seeds-banner.png",
  "flower-seeds": "/flower-seeds-banner.png",
  "potting-mix": "/potting-mix-banner.png",
  "biostimulants": "/biostimulants-banner.png",
  "organic-pest-control": "/organic-pest-control-banner.png",
  "hand-tools": "/hand-tools-banner.png",
  "watering": "/watering-banner.png",
  "accessories": "/accessories-banner.png",
};


function CategoryPageWrapper() {
  return (
    <CartProvider>
      <div className="min-h-screen bg-background font-sans">
        <Header />
        <main>
          <CategoryPage />
        </main>
        <Footer />
        <CartDrawer />
      </div>
    </CartProvider>
  );
}

function CategoryPage() {
  const { id } = Route.useParams();
  const fetchProducts = useServerFn(listProducts);
  const { data: products = [], isPending: productsPending } = useQuery({
    queryKey: ["products", "public"],
    queryFn: () => fetchProducts(),
  });

  const fetchContent = useServerFn(getCategoryContent);
  const { data: dynamicContent, isPending: contentPending } = useQuery({
    queryKey: ["category-content", id],
    queryFn: () => fetchContent({ data: id }),
  });

  // Convert id from kebab-case back to Title Case to match tags
  // e.g., 'vegetable-seeds' -> 'Vegetable Seeds'
  const categoryName = id.split("-").map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(" ");

  if (productsPending || contentPending) {
    return <PageLoader />;
  }

  // Filter products by tag (case insensitive match)
  const categoryProducts = products.filter((p) =>
    p.tags && p.tags.some(tag => tag.toLowerCase() === categoryName.toLowerCase())
  );

  const bgImage = categoryImages[id];

  return (
    <div className="w-full">
      {/* Hero Header with Background Image (contains title generated by AI) */}
      {bgImage && (
        <div
          className="relative w-full h-[300px] md:h-[400px] lg:h-[500px] bg-cover bg-center bg-no-repeat mb-8"
          style={{ backgroundImage: `url(${bgImage})` }}
        >
        </div>
      )}

      <div className={`mx-auto w-full max-w-7xl px-4 pb-8 lg:px-8 lg:pb-12 ${bgImage ? 'pt-0' : 'pt-4 lg:pt-8'}`}>
        <Reveal variant="up">
          <div className="text-center max-w-3xl mx-auto mb-12">
            <h1 className="text-3xl md:text-4xl font-bold text-forest mb-4">{categoryName}</h1>
            <p className="text-lg text-muted-foreground">
              {dynamicContent?.description || `Explore our collection of ${categoryName.toLowerCase()} and find the perfect addition to your space.`}
            </p>
          </div>
        </Reveal>

        {dynamicContent?.gallery && dynamicContent.gallery.length > 0 && (
          <Reveal variant="up">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-16">
              {dynamicContent.gallery.map((img: string, idx: number) => (
                <div key={idx} className="relative h-64 md:h-80 rounded-2xl overflow-hidden group shadow-sm">
                  <img 
                    src={img} 
                    alt={`${categoryName} showcase ${idx + 1}`}
                    className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-black/10 group-hover:bg-transparent transition-colors duration-500"></div>
                </div>
              ))}
            </div>
          </Reveal>
        )}

        {categoryProducts.length > 0 ? (
          <Reveal variant="up">
            <div className="grid grid-cols-2 gap-4 sm:gap-6 md:grid-cols-3 lg:grid-cols-4">
              {categoryProducts.map((p) => (
                <ProductCard key={p.id} product={p} />
              ))}
            </div>
          </Reveal>
        ) : (
          <Reveal variant="up">
            <div className="py-20 text-center border border-dashed border-border rounded-3xl bg-secondary/30">
              <h3 className="text-xl font-semibold text-forest mb-2">Products available shortly</h3>
              <p className="text-muted-foreground">
                We couldn't find any products in the "{categoryName}" category right now. Our team will update the products shortly if they become available!
              </p>
            </div>
          </Reveal>
        )}
      </div>
    </div>
  );
}
