import { createFileRoute } from "@tanstack/react-router";
import { Header } from "@/components/store/Header";
import { Footer } from "@/components/store/Sections";
import { CartDrawer } from "@/components/store/CartDrawer";
import { CartProvider } from "@/components/store/cart";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { listProducts } from "@/lib/products.functions";
import { ProductCard } from "@/components/store/ProductCard";
import { Loader2, Leaf } from "lucide-react";
import { Reveal } from "@/components/store/Reveal";
import { PageLoader } from "@/components/store/PageLoader";

export const Route = createFileRoute("/category/$id")({
  component: CategoryPageWrapper,
});

const categoryImages: Record<string, string> = {
  "vegetable-seeds": "/vegetable-seeds-banner.png",
  "herb-seeds": "/herb-seeds-banner.png",
  "flower-seeds": "/flower-seeds-banner.png",
  "potting-mix": "/potting-mix-banner.png",
  "biostimulants": "/biostimulants-banner.png",
  "organic-pest-control": "/organic-pest-control-banner.png",
  "hand-tools": "/hand-tools-banner.png",
  "watering": "/watering-banner.png",
  "accessories": "/accessories-banner.png",
};

function CategoryPageWrapper() {
  return (
    <CartProvider>
      <div className="min-h-screen bg-background font-sans">
        <Header />
        <main>
          <CategoryPage />
        </main>
        <Footer />
        <CartDrawer />
      </div>
    </CartProvider>
  );
}

function CategoryPage() {
  const { id } = Route.useParams();
  const fetchProducts = useServerFn(listProducts);
  const { data: products = [], isPending } = useQuery({
    queryKey: ["products", "public"],
    queryFn: () => fetchProducts(),
  });

  // Convert id from kebab-case back to Title Case to match tags
  // e.g., 'vegetable-seeds' -> 'Vegetable Seeds'
  const categoryName = id.split("-").map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(" ");

  if (isPending) {
    return <PageLoader />;
  }

  // Filter products by tag (case insensitive match)
  const categoryProducts = products.filter((p) =>
    p.tags && p.tags.some(tag => tag.toLowerCase() === categoryName.toLowerCase())
  );

  const bgImage = categoryImages[id] || "https://images.unsplash.com/photo-1466692476877-36151476f183?w=1600&q=80";

  return (
    <div className="w-full">
      {/* Hero Header with Background Image (contains title generated by AI) */}
      <div
        className="relative w-full h-[300px] md:h-[400px] lg:h-[500px] bg-cover bg-center bg-no-repeat"
        style={{ backgroundImage: `url(${bgImage})` }}
      >
      </div>

      <div className="mx-auto w-full max-w-7xl px-4 py-8 lg:px-8 lg:py-12">
        <Reveal variant="up">
          <p className="text-center text-lg text-muted-foreground max-w-2xl mx-auto mb-10">
            Explore our collection of {categoryName.toLowerCase()} and find the perfect addition to your space.
          </p>
        </Reveal>

        {categoryProducts.length > 0 ? (
          <Reveal variant="up">
            <div className="grid grid-cols-2 gap-4 sm:gap-6 md:grid-cols-3 lg:grid-cols-4">
              {categoryProducts.map((p) => (
                <ProductCard key={p.id} product={p} />
              ))}
            </div>
          </Reveal>
        ) : (
          <Reveal variant="up">
            <div className="py-20 text-center border border-dashed border-border rounded-3xl bg-secondary/30">
              <h3 className="text-xl font-semibold text-forest mb-2">No products found</h3>
              <p className="text-muted-foreground">
                We couldn't find any products in the "{categoryName}" category right now. You can add products to this category from the Admin Dashboard by adding "{categoryName}" to their tags!
              </p>
            </div>
          </Reveal>
        )}
      </div>
    </div>
  );
}
